### Create new user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email":"qqq@test.com", 
    "password": "qqq"
}

### Get user by ID
GET http://localhost:3000/auth/2

### Find all users with given email
GET http://localhost:3000/auth?email=test@test.com

### Delete user by ID
DELETE http://localhost:3000/auth/1

### Update user by ID
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email":"raul@raul.com",
    "password":"newpassword"
}